name: mealmatrix
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: any

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/Meal Matrix Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/images/Meal Matrix Logo.png"

# Flutter-specific configuration
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/Meal Matrix Logo.png
    - lib/assets/images/1.png
    - lib/assets/images/kottu.jpg
    - lib/assets/images/Audi.jpg
    - lib/assets/images/Edge.jpeg
    - lib/assets/images/Hostel.jpeg
    - lib/assets/images/Finagle.jpg
    - lib/assets/images/DefaultProfile.png