name: mealmatrix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  file_picker: ^10.0.0
  app_links: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/Meal Matrix Logo.png
    - lib/assets/images/kottu.jpg
    - lib/assets/images/Audi.jpg
    - lib/assets/images/Edge.jpeg
    - lib/assets/images/Hostel.jpeg
    - lib/assets/images/Finagle.jpg
    - lib/assets/images/DefaultProfile.png
    - lib/assets/images/branding.png
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/Meal Matrix Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/images/Meal Matrix Logo.png"

flutter_native_splash:
  color: "#42a5f5"
  image: "lib/assets/images/splash_logo.png"
  branding: "lib/assets/images/branding.png"
  branding_mode: "bottom"
  android: true
  ios: true                  